### ISSUE TITLE
Can't create database table

### ISSUE THREAD

**Issue by fenixkim** [bnomei/kirby3-mysql-cachedriver#1]
https://github.com/bnomei/kirby3-mysql-cachedriver/blob/1232c5628559cdecfac426df250bd3a7ade6b045/classes/MySQLCache.php#L66

Hello,

It seems that there is a problem, the plugin does not create the table by itself unless the VISIBLE keyword is removed from the creation query. Maybe something is missing on my side.

Thanks.

**Comment by bnomei** [comment]
thanks @fenixkim for reporting the issue
